apiVersion: v1
kind: Service
metadata:
  name: math-api-service
spec:
  type: NodePort
  selector:
    app: math-api
  ports:
  - port: 8000
    targetPort: 5005
    nodePort: 30008
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-api
spec:
  selector:
    matchLabels:
      app: math-api
  replicas: 4
  template:
    metadata:
      labels:
        app: math-api
    spec:
      containers:
      - name: math-api
        image: math-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5005